Pstryk82\LeagueBundle\Domain\ReadModel\Projection\AbstractParticipantProjection:
    type: entity
    table: abstract_participant
    repositoryClass: Pstryk82\LeagueBundle\Repository\AbstractParticipantRepository
    inheritanceType: JOINED
    discriminatorColumn:
        name: discriminator
        type: string
        length: 255
    id:
        id:
            type: string
            length: '13'
            id: true
            generator:
                strategy: NONE
            options:
                fixed: true
            
    manyToOne:
        team:
            targetEntity: Pstryk82\LeagueBundle\Domain\ReadModel\Projection\TeamProjection
            inversedBy: participants
            joinColumn:
                onDelete: cascade
            fetch: EAGER
        competition:
            targetEntity: Pstryk82\LeagueBundle\Domain\ReadModel\Projection\CompetitionProjection
            inversedBy: participants
            joinColumn:
                onDelete: cascade
            fetch: EAGER
    oneToMany:
        games:
            targetEntity: Pstryk82\LeagueBundle\Domain\ReadModel\Projection\GameProjection
            mappedBy: homeTeam
            mappedBy: awayTeam
            fetch: EAGER

    lifecycleCallbacks: {  }
