Pstryk82\LeagueBundle\Domain\ReadModel\Projection\AbstractParticipantProjection:
    type: entity
    table: abstract_participant
    repositoryClass: Pstryk82\LeagueBundle\Repository\AbstractParticipantRepository
    inheritanceType: JOINED
    discriminatorColumn:
        name: discriminator
        type: string
        length: 255
    id:
        id:
            type: string
            id: true
            generator:
                strategy: NONE
            
    manyToOne:
        team:
            targetEntity: Pstryk82\LeagueBundle\Domain\ReadModel\Projection\TeamProjection
            inversedBy: participants
            joinColumn:
                onDelete: cascade
        competition:
            targetEntity: Pstryk82\LeagueBundle\Domain\ReadModel\Projection\CompetitionProjection
            inversedBy: participants
            joinColumn:
                onDelete: cascade
#    oneToMany:
#        games:
#            targetEntity: AppBundle\Entity\Game
#            mappedBy: homeTeam
#            mappedBy: awayTeam
#
    lifecycleCallbacks: {  }
