AppBundle\Entity\AbstractParticipant:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\AbstractParticipantRepository
    inheritanceType: JOINED
    discriminatorColumn:
        name: discriminator
        type: string
        length: 255
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
            
    manyToOne:
        team:
            targetEntity: AppBundle\Entity\Team
            inversedBy: participants
            joinColumn:
                onDelete: cascade
        competition:
            targetEntity: AppBundle\Entity\Competition
            inversedBy: participants
            joinColumn:
                onDelete: cascade
    oneToMany:
        games:
            targetEntity: AppBundle\Entity\Game
            mappedBy: homeTeam
            mappedBy: awayTeam
    
    lifecycleCallbacks: {  }
