AppBundle\Entity\Game:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\GameRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        played:
            type: boolean
        homeTeamScore:
            type: integer
            nullable: true
        awayTeamScore:
            type: integer
            nullable: true
        onNeutralGround:
            type: boolean
        beginningTime:
            type: datetime
            nullable: true
    manyToOne:
        competition:
            targetEntity: AppBundle\Entity\Competition
            inversedBy: games
        homeParticipant:
            targetEntity: AppBundle\Entity\AbstractParticipant
            inversedBy: games
        awayParticipant:
            targetEntity: AppBundle\Entity\AbstractParticipant
            inversedBy: games
        winner:
            targetEntity: AppBundle\Entity\AbstractParticipant
            
    lifecycleCallbacks: {  }
