AppBundle\Entity\League:
    type: entity
    table: league
    repositoryClass: AppBundle\Repository\LeagueRepository
    fields:
        pointsForWin:
            type: smallint
        pointsForDraw:
            type: smallint
        pointsForLose:
            type: smallint
        numberOfLegs:
            type: smallint
    lifecycleCallbacks: {  }
