AppBundle\Entity\Team:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\TeamRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
        rank:
            type: integer
        stadium:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
