services:
    pstryk82.league.event_storage:
        class: Pstryk82\LeagueBundle\Storage\EventStorage
        arguments:
            - '@pstryk82.league.stored_event_repository'
            - '@doctrine.orm.events_entity_manager'

    pstryk82.league.stored_event_repository:
        class: Pstryk82\LeagueBundle\Repository\StoredEventRepository
        factory: ['@doctrine.orm.events_entity_manager', getRepository]
        arguments:
            - Pstryk82\LeagueBundle\Entity\StoredEvent

    pstryk82.league.event_bus:
        class: Pstryk82\LeagueBundle\EventEngine\EventBus

    pstryk82.league.listener.league:
        class: Pstryk82\LeagueBundle\Domain\ReadModel\Listener\LeagueEventListener
        arguments:
            - '@pstryk82.league.event_bus'
            - '@pstryk82.league.projection_storage'

    pstryk82.league.listener.team:
        class: Pstryk82\LeagueBundle\Domain\ReadModel\Listener\TeamEventListener
        arguments:
            - '@pstryk82.league.event_bus'
            - '@pstryk82.league.projection_storage'

    pstryk82.league.projection_storage:
        class: Pstryk82\LeagueBundle\Storage\ProjectionStorage
        arguments:
            - '@pstryk82.league.league_projection_repository'
            - '@doctrine.orm.projections_entity_manager'

    pstryk82.league.league_projection_repository:
        class: Pstryk82\LeagueBundle\Repository\LeagueProjectionRepository
        factory: ['@doctrine.orm.projections_entity_manager', getRepository]
        arguments:
            - Pstryk82\LeagueBundle\Domain\ReadModel\Projection\LeagueProjection

    pstryk82.league.listener.league_participant:
        class: Pstryk82\LeagueBundle\Domain\ReadModel\Listener\LeagueParticipantEventListener
        arguments:
            - '@pstryk82.league.event_bus'
            - '@pstryk82.league.projection_storage'

    pstryk82.league.listener.game:
        class: Pstryk82\LeagueBundle\Domain\ReadModel\Listener\GameEventListener
        arguments:
            - '@pstryk82.league.event_bus'
            - '@pstryk82.league.projection_storage'